app.3rdparty.neverbounce:
  user: yugFZcE4
  secret: pLYIm6P#Oh9dCb1

tui:
  password: #B3Mdwp9
  username: CC2SavvyMoney
  account.code: 123456789

db:
  username: credit-sandbox-user
  password: m8t5e34w

membership.db:
  username: staging
  password: staging
  encryption.key: JZNFTwPzyAeD9kxGRzvfBuHx5zr9dVoqL61rqSbcfNCDqxAgLNKPpdX7Dthoqr1

savvy.v2:
  ssn-hash-salt: $2a$10$GZEuOWS5HuMU2URdevsalt
  ssn-security-prefix-suffix: devprefsuf

atb.password: ABC
